server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: study
    password: study12

  cloud:
    config:
      server:
        git:
          uri: https://github.com/baekinjun/msa-configurations

encrypt:
  key: bts-key

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh